bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
set-option -g history-limit 10000
set-option -a terminal-features 'xterm-256color:RGB'
set-option -sg escape-time 10
set-option -g focus-events on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g status-right "#(~/.tmux/git_status.sh #{pane_current_path})"
set -g status-interval 5

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g update-environment "SSH_AUTH_SOCK"
set -g set-clipboard on
